### PR TITLE
Yeoman generator

### PR DESCRIPTION
**Pull request by cexbrayat**
My friday afternoon experimentation : building a Yeoman generator for quizz.

It's quite simple, but not feature complete. You can test it with :

```
grunt // to have an up to date dist directory
cd generator-quizz
npm install
npm link
```

This step is necessary to test, but if we publish the generator, it will be useless.

Then in an empty directory

```
npm install -g yo // if you don't have Yeoman installed
yo quizz
```

This will generate the sample quizz in your directory!

You can then add a question with

```
yo quizz:checkbox 3
```

(if you want a new question with 3 checkboxes, only checkboxes are supported for now).

Give it a try and tell me what you think!

### CODE REVIEW

**Comment by clacote** [comment]
That works.

Don't know if it's a bug: no keyboard shortcuts (nor Enter neither n or right arrow move to next question).
And a couple of JS errors as soon as generated html file is open :

```
TypeError: Cannot call method 'replace' of null
    at makeHtml (file:///Users/sryl/Workspace/yo-quizz/js/showdown.js:62:1100)
    at Object.fn (file:///Users/sryl/Workspace/yo-quizz/js/markdown.js:17:34)
    at Object.g.$digest (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:103:134)
    at Object.g.$apply (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:105:154)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:320
    at Object.d [as invoke] (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:29:164)
    at Mb.c (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:228)
    at Mb (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:451)
    at Hc (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:4)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:182:71 angular.min.js:79
TypeError: Cannot call method 'replace' of undefined
    at makeHtml (file:///Users/sryl/Workspace/yo-quizz/js/showdown.js:62:1100)
    at Object.fn (file:///Users/sryl/Workspace/yo-quizz/js/markdown.js:17:34)
    at Object.g.$digest (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:103:134)
    at Object.g.$apply (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:105:154)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:320
    at Object.d [as invoke] (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:29:164)
    at Mb.c (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:228)
    at Mb (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:451)
    at Hc (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:4)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:182:71 angular.min.js:79
TypeError: Cannot call method 'replace' of undefined
    at makeHtml (file:///Users/sryl/Workspace/yo-quizz/js/showdown.js:62:1100)
    at Object.fn (file:///Users/sryl/Workspace/yo-quizz/js/markdown.js:17:34)
    at Object.g.$digest (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:103:134)
    at Object.g.$apply (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:105:154)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:320
    at Object.d [as invoke] (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:29:164)
    at Mb.c (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:228)
    at Mb (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:451)
    at Hc (file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:17:4)
    at file:///Users/sryl/Workspace/yo-quizz/js/angular.min.js:182:71 angular.min.js:79
```

**Comment by cexbrayat** [comment]
Weird, I've got the shortcuts and no error displayed...

Maybe the question you added fucked it up : if you open `js/example-quizz.js`, is there anything wrong?

**Comment by clacote** [comment]
If fact, I didn't add any question when I tried.

`js/example-quizz.js` :

``` JavaScript
var quizz = {
    title: 'Example Quizz',
    description: 'This quizz will test your knowledge about AngularJS',
    questions: [
        {
            type: 'radio',
            text: '**AngularJS** is a...',
            answers: [
                {
                    text: 'Java framework',
                    correct: false
                },
                {
                    text: 'JavaScript Framework',
                    correct: true
                },
                {
                    text: 'Ruby Framework',
                    correct: false
                }
            ]
        },
        {
            type: 'free',
            text: 'What is the name of the directive used to *loop* over elements?',
            answers: ['ngRepeat', 'ng-repeat']
        },
        {
            type: 'checkbox',
            text: 'Which tools can help develop [AngularJS](http://angularjs.org) applications?',
            answers: [
                {
                    text: 'Excel',
                    correct: false
                },
                {
                    text: 'Grunt',
                    correct: true
                },
                {
                    text: 'Karma',
                    correct: true
                },
                {
                    text: 'A hammer',
                    correct: false
                }
            ],
            explanation: 'Here\'s what each tool is for:\n\n' +
                '- Excel is a Microsoft spreadsheet;\n' +
                '- Grunt is used to execute various tasks like minifying JS or CSS files;\n' +
                '- Karma is a test runner that executes JavaScript tests in various browsers;\n' +
                '- A hammer is used to knock on nails, or on anything else you could imagine.'
        }
    ]
};
angular.module("example-quizz", ['quizz', 'btford.markdown', 'ngAnimate']);
angular.module("example-quizz").constant('quizz', quizz);

var quizzWithoutPreviousButton = angular.extend({}, quizz);
quizzWithoutPreviousButton.options = {
    showPrevious: false
};
angular.module("example-quizz").constant('quizzWithoutPreviousButton', quizzWithoutPreviousButton);
```

`js/quizz.js` :

``` JavaScript
angular.module('quizz', ['controllers-quizz']);

angular.module("controllers-quizz", []).controller('QuizzCtrl', ['$scope', '$window', '$injector', function($scope, $window, $injector) {
    $scope.started = false;
    $scope.finished = false;
    $scope.resultSelector  = 'all';

    var defaultQuizz = {
        options: {
            showPrevious: true
        }
    };

    $scope.initWithConstant = function(constant) {
        $scope.init($injector.get(constant));
    };

    $scope.init = function(quizz) {
        $scope.quizz = angular.extend({}, defaultQuizz, quizz);
        $scope.started = false;
        $scope.finished = false;
        $scope.currentQuestion = null;
        $scope.resultFilter = $scope.allResultFilter;
    };

    $scope.start = function() {
        $scope.started = true;
        $scope.currentQuestion = $scope.quizz.questions[0];
    };

    function questionIndex() {
        return $scope.quizz.questions.indexOf($scope.currentQuestion);
    }

    function quizzLength() {
        return $scope.quizz.questions.length;
    }

    $scope.questionIndex = questionIndex;

    $scope.questionOddity = function() {
        return questionIndex() % 2 == 0 ? 'even' : 'odd';
    };

    $scope.hasNext = function() {
        return questionIndex() < quizzLength() - 1;
    };

    $scope.hasPrevious = function() {
        return questionIndex() > 0;
    };

    $scope.showNext = $scope.hasNext;

    $scope.showPrevious = function() {
        return $scope.hasPrevious() && $scope.quizz.options.showPrevious;
    };

    $scope.next = function() {
        $scope.currentQuestion = $scope.quizz.questions[questionIndex() + 1];
    };

    $scope.previous = function() {
        $scope.currentQuestion = $scope.quizz.questions[questionIndex() - 1];
    };

    $scope.finish = function() {
        $scope.currentQuestion = null;
        $scope.finished = true;
    };

    function isAnswerCorrect(question) {
        if (question.type == 'radio') {
            return question.selectedAnswer && question.selectedAnswer.correct;
        }
        else if (question.type == 'checkbox') {
            return question.answers.every(function(answer) {
                return ((answer.correct && answer.checked) || (!answer.correct && !answer.checked));
            });
        }
        else if (question.type == 'free') {
            return question.typedAnswer && question.answers.indexOf(question.typedAnswer.trim()) >= 0;
        }
        else {
            return false;
        }
    }

    $scope.isAnswerCorrect = isAnswerCorrect;

    $scope.getScore = function() {
        return $scope.quizz.questions.filter(isAnswerCorrect).length;
    };

    $scope.isAnswerSelected = function(question, answer) {
        if (question.type == 'radio') {
            return question.selectedAnswer === answer;
        }
        else {
            return answer.checked;
        }
    };

    $scope.allResultFilter = function(question) {
        return true;
    };

    $scope.errorsOnlyResultFilter = function(question) {
        return !isAnswerCorrect(question);
    };
}]);
```

**Comment by cexbrayat** [comment]
Ha! I think I know : you have to build the whole project with : 

```
 grunt
```

to have an up to date `dist` directory, which is used by the generator.

**Comment by clacote** [comment]
``` Shell
➜  yo-quizz  grunt
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

**Comment by cexbrayat** [comment]
Grunt should be run in the whole project, not the generator.

**Comment by clacote** [comment]
That works! keyboard shortcuts OK and no more JS errors.

**Pull request closed without merging**
